# fly.toml app configuration file generated for speech-assistant on 2024-10-16T11:34:19-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'speech-assistant'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 5050
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
